name: booking-reservation
version: 0.1.0.0
github: "githubuser/booking-reservation"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/booking-reservation#readme>

dependencies:
  - base >= 4.7 && < 5
  - scotty
  - time
  - text
  - mtl
  - aeson
  - bytestring
  - wai
  - wai-extra
  - warp
  - base-compat
  - postgresql-simple
  - uuid
  - resource-pool
  - co-log
  - http-types
  - test-framework
  - test-framework-quickcheck2
  - test-framework-hunit
  - QuickCheck
  - HUnit
  - postgresql-simple
  - resource-pool
  - containers
  - quickcheck-instances

library:
  source-dirs: src

executables:
  booking-reservation-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - booking-reservation

tests:
  booking-reservation-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - booking-reservation
